builds:
  - binary: dev-proxy
    goos:
      - darwin

    goarch:
      - amd64
      - arm64

    goarm:
      - 6
      - 7

    env:
      - CGO_ENABLED=1  #see https://github.com/golang/go/issues/24383
